development:
  adapter: postgresql
  encoding: unicode
  database: gut_production
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: gut_production
  host: localhost
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gut_production
  host: localhost
  username: postgres
  password:
